//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package armadp

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"runtime/debug"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"golang.org/x/net/http2"
)

var (
	ctx            context.Context
	subscriptionId string
	cred           azcore.TokenCredential
	err            error
	con            *arm.Connection
	mockHost       string
)

func TestOperations_List(t *testing.T) {
	// From example List operations
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewOperationsClient(con)
	pager := client.List(&OperationsListOptions{})
	for pager.NextPage(ctx) {
		if err := pager.Err(); err != nil {
			t.Fatalf("failed to advance page: %v", err)
		}
	}
}

func TestAccounts_CheckNameAvailability(t *testing.T) {
	// From example AccountCheckNameAvailability
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	_, err := client.CheckNameAvailability(ctx,
		AccountCheckNameAvailabilityParameters{
			Name: to.StringPtr("adp1"),
			Type: TypeMicrosoftAutonomousDevelopmentPlatformAccounts.ToPtr(),
		},
		&AccountsCheckNameAvailabilityOptions{})
	if err != nil {
		t.Fatal(err)
	}
}

func TestAccounts_List(t *testing.T) {
	// From example List accounts
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	pager := client.List(&AccountsListOptions{})
	for pager.NextPage(ctx) {
		if err := pager.Err(); err != nil {
			t.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range pager.PageResponse().Value {
			fmt.Printf("Account.ID: %s\n", *v.ID)
			if v.ID == nil {
				t.Fatal("Account.ID should not be nil!")
			}
		}
	}
}

func TestAccounts_ListByResourceGroup(t *testing.T) {
	// From example List accounts by resource group
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	pager := client.ListByResourceGroup("adpClient",
		&AccountsListByResourceGroupOptions{})
	for pager.NextPage(ctx) {
		if err := pager.Err(); err != nil {
			t.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range pager.PageResponse().Value {
			fmt.Printf("Account.ID: %s\n", *v.ID)
			if v.ID == nil {
				t.Fatal("Account.ID should not be nil!")
			}
		}
	}
}

func TestAccounts_Get(t *testing.T) {
	// From example Get account
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	res, err := client.Get(ctx,
		"adpClient",
		"sampleacct",
		&AccountsGetOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Account.ID == nil {
		t.Fatal("Account.ID should not be nil!")
	}
}

func TestAccounts_Update(t *testing.T) {
	// From example Patch account
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	poller, err := client.BeginUpdate(ctx,
		"adpClient",
		"sampleacct",
		&AccountsBeginUpdateOptions{Parameters: &AccountPatch{
			Properties: &AccountProperties{},
		},
		})
	if err != nil {
		t.Fatal(err)
	}
	res, err := poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	if res.Account.ID == nil {
		t.Fatal("Account.ID should not be nil!")
	}
}

func TestAccounts_CreateOrUpdate(t *testing.T) {
	// From example Put account
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	poller, err := client.BeginCreateOrUpdate(ctx,
		"adpClient",
		"sampleacct",
		&AccountsBeginCreateOrUpdateOptions{Parameters: &Account{
			TrackedResource: TrackedResource{
				Location: to.StringPtr("Global"),
			},
			Properties: &AccountProperties{},
		},
		})
	if err != nil {
		t.Fatal(err)
	}
	res, err := poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	if res.Account.ID == nil {
		t.Fatal("Account.ID should not be nil!")
	}
}

func TestAccounts_Delete(t *testing.T) {
	// From example Delete account
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewAccountsClient(con,
		"subid")
	poller, err := client.BeginDelete(ctx,
		"adpClient",
		"sampleacct",
		&AccountsBeginDeleteOptions{})
	if err != nil {
		t.Fatal(err)
	}
	_, err = poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
}

func TestDataPools_List(t *testing.T) {
	// From example List Data Pools
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewDataPoolsClient(con,
		"subid")
	pager := client.List("adpClient",
		"sampleacct",
		&DataPoolsListOptions{})
	for pager.NextPage(ctx) {
		if err := pager.Err(); err != nil {
			t.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range pager.PageResponse().Value {
			fmt.Printf("DataPool.ID: %s\n", *v.ID)
			if v.ID == nil {
				t.Fatal("DataPool.ID should not be nil!")
			}
		}
	}
}

func TestDataPools_Get(t *testing.T) {
	// From example Get Data Pool
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewDataPoolsClient(con,
		"subid")
	res, err := client.Get(ctx,
		"adpClient",
		"sampleacct",
		"sampledp",
		&DataPoolsGetOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if res.DataPool.ID == nil {
		t.Fatal("DataPool.ID should not be nil!")
	}
}

func TestDataPools_Update(t *testing.T) {
	// From example Patch Data Pool
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewDataPoolsClient(con,
		"subid")
	poller, err := client.BeginUpdate(ctx,
		"adpClient",
		"sampleacct",
		"sampledp",
		&DataPoolsBeginUpdateOptions{Parameters: &DataPoolPatch{
			Properties: &DataPoolBaseProperties{
				Locations: []*DataPoolLocation{
					{
						Name: to.StringPtr("westus"),
					}},
			},
		},
		})
	if err != nil {
		t.Fatal(err)
	}
	res, err := poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	if res.DataPool.ID == nil {
		t.Fatal("DataPool.ID should not be nil!")
	}
}

func TestDataPools_CreateOrUpdate(t *testing.T) {
	// From example Put Data Pool
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewDataPoolsClient(con,
		"subid")
	poller, err := client.BeginCreateOrUpdate(ctx,
		"adpClient",
		"sampleacct",
		"sampledp",
		&DataPoolsBeginCreateOrUpdateOptions{Parameters: &DataPool{
			Properties: &DataPoolProperties{
				DataPoolBaseProperties: DataPoolBaseProperties{
					Locations: []*DataPoolLocation{
						{
							Name: to.StringPtr("westus"),
							Encryption: &DataPoolEncryption{
								KeyName:              to.StringPtr("key1"),
								KeyVaultURI:          to.StringPtr("https://vaulturi"),
								KeyVersion:           to.StringPtr("123"),
								UserAssignedIdentity: to.StringPtr("/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id1"),
							},
						}},
				},
			},
		},
		})
	if err != nil {
		t.Fatal(err)
	}
	res, err := poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	if res.DataPool.ID == nil {
		t.Fatal("DataPool.ID should not be nil!")
	}
}

func TestDataPools_Delete(t *testing.T) {
	// From example Delete Data Pool
	defer func() {
		if r := recover(); r != nil {
			t.Fatal("stacktrace from panic: \n" + string(debug.Stack()))
		}
	}()
	client := NewDataPoolsClient(con,
		"subid")
	poller, err := client.BeginDelete(ctx,
		"adpClient",
		"sampleacct",
		"sampledp",
		&DataPoolsBeginDeleteOptions{})
	if err != nil {
		t.Fatal(err)
	}
	_, err = poller.PollUntilDone(ctx, 30*time.Second)
	if err != nil {
		t.Fatal(err)
	}
}

// TestMain will exec each test
func TestMain(m *testing.M) {
	setUp()
	retCode := m.Run() // exec test and this returns an exit code to pass to os
	tearDown()
	os.Exit(retCode)
}

func getEnv(key, fallback string) string {
	if value, ok := os.LookupEnv(key); ok {
		return value
	}
	return fallback
}

func setUp() {
	ctx = context.Background()
	subscriptionId = getEnv("SUBSCRIPTION_ID", "00000000-0000-0000-0000-000000000000")
	mockHost = getEnv("AZURE_VIRTUAL_SERVER_HOST", "https://localhost:8443")

	tr := &http.Transport{}
	if err := http2.ConfigureTransport(tr); err != nil {
		fmt.Printf("Failed to configure http2 transport: %v", err)
	}
	tr.TLSClientConfig.InsecureSkipVerify = true
	client := &http.Client{Transport: tr}
	cred, err = azidentity.NewEnvironmentCredential(&azidentity.EnvironmentCredentialOptions{AuthorityHost: mockHost, HTTPClient: client})
	if err != nil {
		panic(err)
	}

	con = arm.NewConnection(mockHost, cred, &arm.ConnectionOptions{
		Logging: policy.LogOptions{
			IncludeBody: true,
		},
		HTTPClient: client,
	})
}

func tearDown() {

}
